// <auto-generated/>

using shared.Models;

namespace shared.Interfaces;

public interface IPolicyController
{
    public Task<List<Policy>> GetAll();
    public Task<Policy> GetOne(string key);
    public Task<Policy> Update(Policy policy);
    public Task Sync(List<Policy> policies);
}
