// <auto-generated/>

using shared.Models;

namespace shared.Interfaces;

public interface IPolicyController
{
    public Task<List<Policy>> GetAll();
    public Task<Policy> Update(string key, Policy policy);
    public Task<Policy> Create(string key);
}
