# docker compose -f design.yaml up -d

version: '3.1'

services:
  light:
    image: "structurizr/lite"
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - "./design/:/usr/local/structurizr"
