version: '3.1'

# docker compose -f stack.yml up -d

services:
  db:
    container_name: "devops_data"
    image: "postgres:14.3"
    restart: always
    environment:
      POSTGRES_PASSWORD: "testpwd"
    ports:
      - "5430:5432"
    volumes:
      - "./.data/:/var/lib/postgresql/data"
  