// <auto-generated/>

using shared.Interfaces;
using System.Net.Http.Json;

namespace shared.services;

public class SchemaService : ISchemaController
{
    private readonly HttpClient _client;
    
    private const string Prefix = "/Schema";
    
    public SchemaService(IHttpClientFactory factory)
    {
        _client = factory.CreateClient("api");
    }

}