// <auto-generated/>

using shared.Interfaces;
using System.Net.Http.Json;

namespace shared.services;

public class UtilService : IUtilController
{
    private readonly HttpClient _client;
    
    private const string Prefix = "/Util";
    
    public UtilService(IHttpClientFactory factory)
    {
        _client = factory.CreateClient("api");
    }

    public async Task<string> Fill()
    {
        var route = $"{Prefix}/fill";

        var httpResponse = await _client.GetAsync(route);
        httpResponse.EnsureSuccessStatusCode();
        return (await httpResponse.Content.ReadFromJsonAsync<string>())!;
    }

    public async Task<string> Test()
    {
        var route = $"{Prefix}/";

        var httpResponse = await _client.GetAsync(route);
        httpResponse.EnsureSuccessStatusCode();
        return (await httpResponse.Content.ReadFromJsonAsync<string>())!;
    }

    public async Task<Dictionary<string,string>> Reader()
    {
        var route = $"{Prefix}/read";

        var httpResponse = await _client.GetAsync(route);
        httpResponse.EnsureSuccessStatusCode();
        return (await httpResponse.Content.ReadFromJsonAsync<Dictionary<string,string>>())!;
    }

}